language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required

before_script:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.0-preview3-004056
  - dotnet restore

script:
  - dotnet build src/msgpack.light
  - dotnet test tests/msgpack.light.tests